services:
  mysql:
    image: mysql:8.0
    container_name: mysql_bd
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: athlete_lab
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: app-java
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
        # Arquivos front públicos
        - ./src/main/webapp/index.jsp:/usr/local/tomcat/webapps/athletelab_web/index.jsp
        - ./src/main/webapp/css:/usr/local/tomcat/webapps/athletelab_web/css
        - ./src/main/webapp/js:/usr/local/tomcat/webapps/athletelab_web/js
        - ./src/main/webapp/banco_imagens:/usr/local/tomcat/webapps/athletelab_web/banco_imagens

        # JSPs dentro de WEB-INF
        - ./src/main/webapp/WEB-INF/admin_treino.jsp:/usr/local/tomcat/webapps/athletelab_web/WEB-INF/admin_treino.jsp
        - ./src/main/webapp/WEB-INF/cadastro.jsp:/usr/local/tomcat/webapps/athletelab_web/WEB-INF/cadastro.jsp
        - ./src/main/webapp/WEB-INF/criar_treino.jsp:/usr/local/tomcat/webapps/athletelab_web/WEB-INF/criar_treino.jsp
        - ./src/main/webapp/WEB-INF/detalhesAtleta.jsp:/usr/local/tomcat/webapps/athletelab_web/WEB-INF/detalhesAtleta.jsp
    environment:
      DB_HOST: mysql
      DB_NAME: athlete_lab
      DB_USER: user
      DB_PASSWORD: 1234