services:

  mysql:
    image: mysql:8.0
    container_name: mysql_bd
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: athlete_lab
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234

    ports:
      - "3307:3306"

    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: app-java

    depends_on:
      mysql:
        condition: service_healthy

    ports:
      - "8080:8080"

    environment:
      DB_HOST: mysql
      DB_NAME: athlete_lab
      DB_USER: user
      DB_PASSWORD: 1234